### ISSUE TITLE
Unable to achieve the performance mentioned in the paper

### ISSUE THREAD

**Issue by gaoyuchris** [yangze0930/NTS-Net#1]
I have trained the model by the code without any change, unfortunately，I can't achieve the performance mentioned in the paper. The parameters I set are "BATCH_SIZE = 16, PROPOSAL_NUM = 6, INPUT_SIZE = (448, 448), LR = 0.001, WD = 1e-4", the only difference is that the learing rate multiplied by 0.1 after 60 epoches and 100 epoches(which is set in your code) . I have trained 143 epoch, but the acc of the test data is just 0.415? I don't know if there is any problem here？ 
![image](https://user-images.githubusercontent.com/15527703/45583083-28246080-b8ee-11e8-84a4-31f53ab97844.png)

**Comment by gaoyuchris** [comment]
I have found the problem for my stupid mistake, and got the performance mentioned in the paper, thanks for the authours

**Comment by mkumar10** [comment]
What was your issue? Was it pytorch version?

**Comment by metro-smiles** [comment]
I was facing the same problem too, was wondering how you were able to solve it?

**Comment by gaoyuchris** [comment]
My pytorch version is pytorch 0.4. My stupid error is that I commented the code of  "net.eval()"   by mistake when evaluating the net on test data.

**Comment by metro-smiles** [comment]
> 
> 
> My pytorch version is pytorch 0.4. My stupid error is that I commented the code of "net.eval()" by mistake when evaluating the net on test data.

I made the same error myself, so really appreciate you sharing this info.
