### ISSUE TITLE
stty: 'standard input': Inappropriate ioctl for device 

### ISSUE THREAD

**Issue by ray-lee-94** [yangze0930/NTS-Net#11]
_, term_width =os.popen('stty size','r').read().split()
ValueError: not enough values to unpack

**Comment by ray-lee-94** [comment]
sorry. I  run the train.py in **pycharm**, I got this  issue.  If i run in the **Terminal**, i is fine.

**Comment by fxle** [comment]
Hello，I also have this problem. Have you solved it now? @VCBE123

**Comment by tectal** [comment]
me, too. How to solve it???

**Comment by franroldans** [comment]
I solved it replacing 

`_, term_width =os.popen('stty size','r').read().split()`

with

```
from shutil import get_terminal_size
term_width, _ = get_terminal_size()
```

**Comment by JingyunLiang** [comment]
You could comment these two lines and use  `term_width=80`.

**Comment by ZQSIAT** [comment]
> I solved it replacing
> 
> `_, term_width =os.popen('stty size','r').read().split()`
> 
> with
> 
> ```
> from shutil import get_terminal_size
> term_width, _ = get_terminal_size()
> ```

It works！
