### ISSUE TITLE
你的代码有个小问题！！！

### ISSUE THREAD

**Issue by gengyanlei** [yangze0930/NTS-Net#29]
我查阅了你的读取数据的代码，发现你读取的图片事RGB通道，而你的Normalize则采用的imagenet的BGR对应的std和mean 值，虽然影响很小，但是会降低一些性能的。我查阅的imagenet的std和mean是按照BGR顺序排列的。

**Comment by boxyao** [comment]
没找到说是按BGR排的呀

**Comment by kolomomo** [comment]
哪里查阅到的? pytorch官方例子也是RGB顺序啊
