### ISSUE TITLE
Time cost on Training

### ISSUE THREAD

**Issue by yy9568** [yangze0930/NTS-Net#3]
Hey,your job is excellent!Recently,I have a task which contains 2000+ classes and 5.6 millions images about cars, I had tried to train BCNN on my dataset, but it spent too much time on convergence of network.I did not get answer after reading your paper. Could you tell me about how long you had trained NTS-Net using CUB dataset on your 4 GPUs machine?Thank you.

**Comment by yangze0930** [comment]
You will need about 10 hours to train 100 epoch on CUB dataset using 4 Titan X, and 100 epoch is enough for CUB.
