### ISSUE TITLE
谢谢作者的无私分享。我想自己制作数据集用此网络试试效果，请问我该怎么标注图片？

### ISSUE THREAD

**Issue by lunchben** [yangze0930/NTS-Net#35]
我是一名初学者，用CUB200数据集测试了此网络，结果跟论文一致，在此感谢作者的贡献和分享。现在我想自己标注一份数据集来测试一下效果，请问我该怎么做？大家有什么建议吗？特别是我应该如何标注自己的数据来适应这个网络方面还有一些问题不太清楚，请各位大佬指点迷津啊。感谢。

**Comment by Javacr** [comment]
你只要将图片分到所属的类别即可。建议不同类别放入不同文件夹，文件夹名为类别名，训练时候，做好数据预处理，将类别名编号，从1开始。

**Comment by lunchben** [comment]
> 你只要将图片分到所属的类别即可。建议不同类别放入不同文件夹，文件夹名为类别名，训练时候，做好数据预处理，将类别名编号，从1开始。

谢谢您。CUB的数据集不仅有bunding box也有一些part局部信息的标签，我不知道我是否需要将我的数据像CUB那样标注，那样的话我应该怎么制作CUB格式的数据集呢？

**Comment by Javacr** [comment]
> > 你只要将图片分到所属的类别即可。建议不同类别放入不同文件夹，文件夹名为类别名，训练时候，做好数据预处理，将类别名编号，从1开始。
> 
> 谢谢您。CUB的数据集不仅有bunding box也有一些part局部信息的标签，我不知道我是否需要将我的数据像CUB那样标注，那样的话我应该怎么制作CUB格式的数据集呢？
看来你是没有理解这篇文章。这篇文章不需要边框，只需要知道子类类别即可。

**Comment by Javacr** [comment]
> > 你只要将图片分到所属的类别即可。建议不同类别放入不同文件夹，文件夹名为类别名，训练时候，做好数据预处理，将类别名编号，从1开始。
> 
> 谢谢您。CUB的数据集不仅有bunding box也有一些part局部信息的标签，我不知道我是否需要将我的数据像CUB那样标注，那样的话我应该怎么制作CUB格式的数据集呢？


看来你是没有理解这篇文章。这篇文章不需要边框，只需要知道子类类别即可。

**Comment by lunchben** [comment]
> > > 你只要将图片分到所属的类别即可。建议不同类别放入不同文件夹，文件夹名为类别名，训练时候，做好数据预处理，将类别名编号，从1开始。
> > 
> > 
> > 谢谢您。CUB的数据集不仅有bunding box也有一些part局部信息的标签，我不知道我是否需要将我的数据像CUB那样标注，那样的话我应该怎么制作CUB格式的数据集呢？
> 
> 看来你是没有理解这篇文章。这篇文章不需要边框，只需要知道子类类别即可。

原来如此，多谢指教。因为刚开始接触深度学习，我感觉逻辑的起点很重要，所以就一直拘泥于数据集的制作。

**Comment by hackjus** [comment]
@lunchben 请问，我运行它这个测试test.py，有问题，你之前能跑通代码？

**Comment by lunchben** [comment]
> @lunchben 请问，我运行它这个测试test.py，有问题，你之前能跑通代码？

我只跑了训练和验证集，没有测试。数据集不够了。
