### ISSUE TITLE
Different test accuracy when testing with different BATCH_SIZE in config.py

### ISSUE THREAD

**Issue by yangxh11** [yangze0930/NTS-Net#46]

**Comment by yangxh11** [comment]
The model is fully trained and saved. When testing, I only change the BATCH_SIZE in config.py and get different test accuracy.

**Comment by giangnguyen2412** [comment]
did you figure out why? i got the same thing here in 2023 :D

**Comment by giangnguyen2412** [comment]
bs8: 0.412
bs128: 0.726
bs256: 0.810

it seems memory is all you need to solve cub-200 lol

**Comment by giangnguyen2412** [comment]
@yangze0930 ! do you know why this problem arises?

**Comment by giangnguyen2412** [comment]
found the problem.
I forgot to set net.eval(). Everything works now.
